=== AionGermany/aion-germany/AL-Game-5.8/data/static_data/housing/scripts.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="lboxes">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" name="lbox" type="LBox"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="id" type="xs:int"/>
    <xs:element name="name" type="xs:string"/>
    <xs:element name="desc" type="xs:string"/>
    <xs:element name="script" type="xs:string"/>
    <xs:element name="icon" type="xs:int"/>
    <xs:complexType name="LBox">
        <xs:sequence>
            <xs:element ref="id"/>
            <xs:element ref="name"/>
            <xs:element ref="desc"/>
            <xs:element ref="script"/>
            <xs:element ref="icon"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== AionGermany/aion-germany/AL-Game-5.8/data/static_data/housing/scripts.xml
<?xml version="1.0" encoding="UTF-8"?>
<lboxes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="scripts.xsd">
    <lbox>
        <id>101</id>
        <name><![CDATA[New Script]]></name>
        <desc><![CDATA[Enter the description.]]></desc>
        <script><![CDATA[function OnInit()
    -- Create the initialization script.
end
]]></script>
        <icon>1</icon>
    </lbox>
    <lbox>
        <id>102</id>
        <name><![CDATA[Greeting]]></name>
        <desc><![CDATA[The butler will say a greeting to an approaching visitor.]]></desc>
        <script><![CDATA[-- You can customize the butler's greeting to match every visitor.
-- Enter the character name in the table below, along with the greeting text and sound for the character's visit.

helloTable = { 
                   ["[kvalue:Name1;Character Name1;str]"] = {"[kvalue:Greeting1;, Hello;str]",    [kvalue:Greet SFX 1;H.Percussion.fx2;fx] },
                   ["[kvalue:Name2;Character Name2;str]"] = {"[kvalue:Greeting2;, Hi;str]",    [kvalue:Greet SFX 2;H.Percussion.fx11;fx] },
                   ["[kvalue:Name3;Character Name3;str]"] = {"[kvalue:Greeting3;, Come on in;str]",  [kvalue:Greet SFX 3;H.Percussion.fx6;fx] },
                 };

-- Check for a character's presence in helloTable, and either use a default greeting or the character appropriate greeting.
function GetHelloString(desc)
    if (helloTable[desc] == nil) then
        return desc.."[kvalue:Default Greet;, Hello, dear.;str]";
    end
        return helloTable[desc][1];
end

function GetHelloSound(desc)
    if (helloTable[desc] == nil) then
        return [kvalue:Default SFX;H.Percussion.fx9;fx];
    end
        return helloTable[desc][2];
end

-- Called on function initialization.
function OnInit()

    -- With the SetSensor command, you can customize the distance the butler recognizes a user.
    -- The butler recognizes the user inside the radius of the first variable.
    -- The butler does not respond if the user is outside the second variable.
    -- For the following code, the butler recognizes a user when he/she comes within a 3m radius.
    -- Again, the butler does not respond when a user passes a 30m radius.
    H.SetSensor(3, 30);

end

-- Calls when a user enters a distance range that the butler can recognize.
function OnUserEntered(desc)

    -- With the PlaySound command, options can be set to play music or a label.
    -- The first variable is to set channels and the second one sets music score.
    -- This line sets 2 labels for channel no. 0.
    H.PlaySound(0, "r[1]r[2]");

    -- Play the effect sound for the respective visitors.
    if (GetHelloSound(desc) ~= nil) then
        -- The SetPercussion command is used for customizing sounds.
        H.SetPercussion(1, GetHelloSound(desc));
        -- "x" refers to SetPercussion, enabling the preset sound.
        H.PlaySound(1, "x");
    end

    -- The butler starts an animation.
    -- The first variable "0" refers to the butler.
    -- The second variable "1" refers to label no. [1] in the PlaySound command.
    -- The third variable is a motion with a waving hand.
    H.StartAnimation(0, 1, [kvalue:Greet Motion;H.Emotion.wave;moti]);

    -- The butler speaks through a speech bubble.
    -- The first variable "2" refers to the label no. [2] in the PlaySound command.
    -- Enter the dialog message of the butler in the second variable.
    H.Say(2, GetHelloString(desc));
end

-- Available Motions for Setup:
--    point, sleep, angry, blush, dance, clap, comfort, drink, eat, laugh, kneel, no, 
--    otl, pat, plead, ready, sad, slap, surprise, taunt, thanks, thunder,
--    useup, victory, yes, wave, boo, charge, dislike, panic, salute, smile,
--    sorry, think, blueflag, twoflag, whiteflag, sing, jump]]></script>
        <icon>4</icon>
    </lbox>
    <lbox>
        <id>116</id>
        <name><![CDATA[Simonerk Says]]></name>
        <desc><![CDATA[Enter the text "Simonerk Says" in the chat window to play the game with the butler.]]></desc>
        <script>
            <![CDATA[
-- You modify how the game is played by changing the command text strings shown below.
g_flagTable = { 
  { "[kvalue:Command1;Simonerk says Lift the Blue Flag;str]",			  [kvalue:Motion1;H.Emotion.blueflag;moti]  },
  { "[kvalue:Command2;Simonerk says Don't lift the white flag, lift the blue flag!;str]", [kvalue:Motion2;H.Emotion.blueflag;moti]  },
  { "[kvalue:Command3;Simonerk says Lift the white flag;str]",			  [kvalue:Motion3;H.Emotion.whiteflag;moti] },
  { "[kvalue:Command4;Simonerk says Don't lift the blue flag, lift the white flag!;str]", [kvalue:Motion4;H.Emotion.whiteflag;moti]  },
  { "[kvalue:Command5;Simonerk says Lift both flags;str]",			  [kvalue:Motion5;H.Emotion.twoflag;moti]   }, 
  { "[kvalue:Command6;Simonerk says Don't lift the blue flag, lift both flags!;str]", [kvalue:Motion6;H.Emotion.twoflag;moti]  },
  { "[kvalue:Command7;Simonerk says Don't lift the white flag, lift both flags!;str]", [kvalue:Motion7;H.Emotion.twoflag;moti]  },
};

-- Called on script initialization.
g_playerName = "";
function OnInit()
    H.SetSensor(20, 30);

    -- Activates the OnSoundPlay function
    H.EnableSoundCallback(1);
	
	g_playerName = H.GetPlayerName();
end

g_userTable       = {};
g_failTable       = {};
g_curFlagCount    = 0;
g_curFlagMotion   = "";
g_inGame          = 0;
g_hostGame        = 0;

function StartGame()
    g_inGame          = 1;
    for k,v in pairs(g_userTable) do g_userTable[k] = 0 end;
    for k,v in pairs(g_failTable) do g_userTable[k] = 0 end;
    g_failTable       = {};
    g_curFlagCount    = 0;
    g_curFlagMotion   = "";
    math.randomseed(H.GetGameTime());
	H.Say(1, "Get ready for Simonerk Says!");
    H.PlaySound(1, "r[1]rrrrr x[2]rrrrr x[3]rrrrr x[4]rrrrr x[5]rrrrr x[6]rrrrr x[7]");
    if (g_hostGame == 1) then
      H.Broadcast("Ready", 0, 0);
    end
end

function AddUser(desc)
    g_userTable[desc] = 0;
end

function OnBroadcasted(fromUser, msg, param1, param2)
    -- Confirm game participation if multiple players are in the house
    if (msg == "Ready") then
	    if (g_hostGame == 0 and g_playerName ~= fromUser) then
	      H.Broadcast("Join", 0, 0);
	    end
	  elseif (msg == "Join") then
	    if (g_hostGame == 1 and g_playerName ~= fromUser) then
	      AddUser(fromUser);
	    end

    -- Win/Lose text display and sound effects	    
	  elseif (string.find(msg, "Win")) then
	    H.SayNoBalloon(1, msg.sub(msg, 8, -1) .. " won!");
	    if (string.find(msg, g_playerName)) then
	      H.SetPercussion(5, H.Percussion.fx7);
	      H.PlaySound(5, "x");
	    end
	  elseif (string.find(msg, "Lose")) then
      H.SayNoBalloon(1, msg.sub(msg, 8, -1) .. " lost!");
	    if (string.find(msg, g_playerName)) then
	      H.SetPercussion(5, H.Percussion.fx4);
	      H.PlaySound(5, "x");
      end
	  end
end

function EndGame()
    for k,v in pairs(g_userTable) do
      H.SayAllNoBalloon(1, "You won the game, "..k);
    end
    for k,v in pairs(g_failTable) do
      H.SayAllNoBalloon(1, "You lost the game, "..k);
    end
    H.PlaySound(4, "r[1]");
    g_hostGame        = 0;
    g_inGame          = 0;
end

function FailUser(desc)
  H.Broadcast("lost" .. desc, 0, 0);
  g_failTable[desc] = 1;
end

function OutFailedUsers()
  for k, v in pairs(g_failTable) do
    g_userTable[k] = nil;
  end
end

function CheckPlayerFlag()
  for k, v in pairs(g_userTable) do
    if (v ~= g_curFlagCount) then
      FailUser(k);
    end
  end
  OutFailedUsers();
end

-- Called when the player uses an emote.
function OnUserEmotion(motion, desc)
  if (motion == H.Emotion.blueflag or motion == H.Emotion.whiteflag or motion == H.Emotion.twoflag) then
	  if (g_hostGame == 1) then
	      if (g_userTable[desc] ~= nil) then
	        if (motion == g_curFlagMotion) then
            H.Broadcast("success" .. desc, 0, 0);
	          g_userTable[desc] = g_curFlagCount;
	        else
	          FailUser(desc);
	          OutFailedUsers();
	        end
	      end
	  end  
	  H.PlaySound(2, "r[1]");
	end
end

function SetRandomFlagType()  
  randVal = math.random(#g_flagTable);
  g_curFlagMotion = g_flagTable[randVal][2];
  randFlagName    = g_flagTable[randVal][1];
  g_curFlagCount  = g_curFlagCount+1;

  H.AlertAll(1, randFlagName);
  H.PlaySound(3, "r[1]");
end

function GetUserCount()
  count = 0;
  for k,v in pairs(g_userTable) do count = count + 1; end
  return count;
end

-- Called when the music plays
function OnSoundPlay(channel, note, len, label)
  if (g_hostGame == 1) then
      if ((1 < label) and (label < 7)) then
        CheckPlayerFlag();
        if (GetUserCount() == 0) then
          EndGame();
        else
          SetRandomFlagType();
        end
      end
      if (label == 7) then
        CheckPlayerFlag();
        EndGame();
      end
  else
      if (label == 7) then
        g_inGame          = 0;
      end
  end
end

function OnUserEntered(desc)
  AddUser(desc);
end

function OnUserSay(str, desc)
  if (string.find(str, "Simonerk Says")) then
    if (g_inGame == 0) then
      if (desc == g_playerName) then
        g_hostGame        = 1;
      end
      StartGame();
    end
  end
end
]]></script>
        <icon>6</icon>
    </lbox>
    <lbox>
        <id>117</id>
        <name><![CDATA[Table Jump]]></name>
        <desc>
            <![CDATA[Enter "Table Jump" in the chat window to start a game of Jump on the Glowing Furniture.  Designate each piece of furniture you want to use as an Outlet by clicking on a number in the Outlet window and then clicking on the piece of furniture you want to use. ]]></desc>
        <script><![CDATA[constStageNum        = 10;
constTableNum         = 6;
constTableNumPerStage = 2;     -- About one-third of constTableNum is good enough.

gsReady  = 0;
gsInGame = 1;

isHost      = false;
gameState   = gsReady;
outletState = {};
userScore   = {};

function OnInit()
  if (constTableNum < 3) then constTableNum = 3; end
  if (constTableNum > 9) then constTableNum = 9; end
