=== AionGermany/aion-germany/AL-Game/data/static_data/locations/abyss_landing/landing_special_locations.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:jxb="http://java.sun.com/xml/ns/jaxb" jxb:version="2.1">
    <xs:include schemaLocation="../../global_types.xsd"/>
    <xs:element name="landing_special">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="landing_special_location" type="LandingSpecial" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="LandingSpecial">
        <xs:attribute name="id" type="xs:int" use="required"/>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="race" type="xs:string" use="required"/>
    </xs:complexType>
</xs:schema>

=== AionGermany/aion-germany/AL-Game-5.8/data/static_data/locations/abyss_landing/landing_special_locations.xml
<?xml version="1.0" encoding="UTF-8"?>
<landing_special xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="landing_special_locations.xsd">
    <!-- ELYOS -->
	<landing_special_location id="1" name="Krotan Guardian Spirit's Monument" race="ELYOS"/>
	<landing_special_location id="2" name="Miren Guardian Spirit's Monument" race="ELYOS"/>
	<landing_special_location id="3" name="Kysis Guardian Spirit's Monument" race="ELYOS"/>
	<landing_special_location id="4" name="Krotan Commander" race="ELYOS"/>
	<landing_special_location id="5" name="Miren Commander" race="ELYOS"/>
	<landing_special_location id="6" name="Kysis Commander" race="ELYOS"/>
	<landing_special_location id="7" name="Ide Cannon Tumon 1 Annihilation Monument" race="ELYOS"/>
	<landing_special_location id="8" name="Ide Cannon Tumon 2 Annihilation Monument" race="ELYOS"/>
	<landing_special_location id="9" name="Artillery Tumon 1 Annihilation Monument" race="ELYOS"/>
	<landing_special_location id="10" name="Artillery Tumon 2 Annihilation Monument" race="ELYOS"/>
	<landing_special_location id="11" name="Wurg The Glacier Annihilation Monument" race="ELYOS"/>
	<landing_special_location id="12" name="Terracrusher Annihilation Monument" race="ELYOS"/>
	<!-- ASMODIANS -->
    <landing_special_location id="13" name="Krotan Guardian Spirit's Monument" race="ASMODIANS"/>
	<landing_special_location id="14" name="Miren Guardian Spirit's Monument" race="ASMODIANS"/>
	<landing_special_location id="15" name="Kysis Guardian Spirit's Monument" race="ASMODIANS"/>
	<landing_special_location id="16" name="Krotan Commander" race="ASMODIANS"/>
	<landing_special_location id="17" name="Miren Commander" race="ASMODIANS"/>
	<landing_special_location id="18" name="Kysis Commander" race="ASMODIANS"/>
	<landing_special_location id="19" name="Ide Cannon Tumon 1 Defeat Monument" race="ASMODIANS"/>
	<landing_special_location id="20" name="Ide Cannon Tumon 2 Defeat Monument" race="ASMODIANS"/>
	<landing_special_location id="21" name="Artillery Tumon 1 Defeat Monument" race="ASMODIANS"/>
	<landing_special_location id="22" name="Artillery Tumon 2 Defeat Monument" race="ASMODIANS"/>
	<landing_special_location id="23" name="Wurg The Glacier Defeat Monument" race="ASMODIANS"/>
	<landing_special_location id="24" name="Terracrusher Defeat Monument" race="ASMODIANS"/>
</landing_special>
