=== AionGermany/aion-germany/AL-Game/data/static_data/cubics/cubics_templates.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="cubics_templates">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="cubics_template" type="CubicsTemplate" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
	
    <xs:complexType name="CubicsTemplate">
		<xs:sequence>
            <xs:element name="core_list" type="StatCoreList" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:int"/>
        <xs:attribute name="name" type="xs:string"/>
		<xs:attribute name="category" type="xs:int"/>
		<xs:attribute name="maxRank" type="xs:int"/>
		<xs:attribute name="quality" type="QualityCoreType" use="required"/>
		<xs:attribute name="itemId" type="xs:int"/>
    </xs:complexType>
	
    <xs:complexType name="StatCoreList">
        <xs:attribute name="id" type="xs:int"/>
		<xs:attribute name="level" type="xs:int"/>
        <xs:attribute name="stat" type="modifiersenum" use="required"/>
		<xs:attribute name="value" type="xs:int"/>
    </xs:complexType>
	
	<xs:simpleType name="QualityCoreType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="GOLD"/>
            <xs:enumeration value="SILVER"/>
            <xs:enumeration value="BRONZE"/>
            <xs:enumeration value="PLATINUM"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== AionGermany/aion-germany/AL-Game/data/static_data/cubics/cubics_templates.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- parsed by phpTools from Aion Germany Group (Mariella) at 2020-04-06 10:00 -->
<cubics_templates xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cubics_templates.xsd">
    <cubics_template id="1" name="Gold Cubelet of Mosbear Life" quality="GOLD" maxRank="5" category="100" itemId="188200023">
        <core_list id="1" level="5" stat="MAXHP" value="429"/>
        <core_list id="2" level="10" stat="MAXHP" value="613"/>
        <core_list id="3" level="15" stat="MAXHP" value="875"/>
        <core_list id="4" level="20" stat="MAXHP" value="1330"/>
        <core_list id="5" level="25" stat="MAXHP" value="1900"/>
    </cubics_template>
    <cubics_template id="2" name="Silver Cubelet of Mosbear Life" quality="SILVER" maxRank="5" category="100" itemId="188200024">
        <core_list id="1" level="10" stat="MAXHP" value="420"/>
        <core_list id="2" level="20" stat="MAXHP" value="600"/>
        <core_list id="3" level="30" stat="MAXHP" value="858"/>
        <core_list id="4" level="40" stat="MAXHP" value="1225"/>
        <core_list id="5" level="50" stat="MAXHP" value="1650"/>
    </cubics_template>
    <cubics_template id="3" name="Bronze Cubelet of Mosbear Life" quality="BRONZE" maxRank="5" category="100" itemId="188200025">
        <core_list id="1" level="20" stat="MAXHP" value="336"/>
        <core_list id="2" level="40" stat="MAXHP" value="480"/>
        <core_list id="3" level="60" stat="MAXHP" value="686"/>
        <core_list id="4" level="80" stat="MAXHP" value="980"/>
        <core_list id="5" level="100" stat="MAXHP" value="1400"/>
    </cubics_template>
    <cubics_template id="4" name="Gold Cubelet of Agrint Spirit" quality="GOLD" maxRank="5" category="101" itemId="188200026">
        <core_list id="1" level="5" stat="MAXMP" value="300"/>
        <core_list id="2" level="10" stat="MAXMP" value="429"/>
        <core_list id="3" level="15" stat="MAXMP" value="613"/>
        <core_list id="4" level="20" stat="MAXMP" value="931"/>
        <core_list id="5" level="25" stat="MAXMP" value="1330"/>
    </cubics_template>
    <cubics_template id="5" name="Silver Cubelet of Agrint Spirit" quality="SILVER" maxRank="5" category="101" itemId="188200027">
        <core_list id="1" level="10" stat="MAXMP" value="294"/>
        <core_list id="2" level="20" stat="MAXMP" value="420"/>
        <core_list id="3" level="30" stat="MAXMP" value="600"/>
        <core_list id="4" level="40" stat="MAXMP" value="858"/>
        <core_list id="5" level="50" stat="MAXMP" value="1155"/>
    </cubics_template>
    <cubics_template id="6" name="Bronze Cubelet of Agrint Spirit" quality="BRONZE" maxRank="5" category="101" itemId="188200028">
        <core_list id="1" level="20" stat="MAXMP" value="235"/>
        <core_list id="2" level="40" stat="MAXMP" value="336"/>
        <core_list id="3" level="60" stat="MAXMP" value="480"/>
        <core_list id="4" level="80" stat="MAXMP" value="686"/>
        <core_list id="5" level="100" stat="MAXMP" value="980"/>
    </cubics_template>
    <cubics_template id="7" name="Gold Cubelet of Trico Blessing" quality="GOLD" maxRank="5" category="102" itemId="188200029">
        <core_list id="1" level="5" stat="HEAL_BOOST" value="10"/>
        <core_list id="2" level="10" stat="HEAL_BOOST" value="15"/>
        <core_list id="3" level="15" stat="HEAL_BOOST" value="21"/>
        <core_list id="4" level="20" stat="HEAL_BOOST" value="32"/>
        <core_list id="5" level="25" stat="HEAL_BOOST" value="46"/>
    </cubics_template>
    <cubics_template id="8" name="Silver Cubelet of Trico Blessing" quality="SILVER" maxRank="5" category="102" itemId="188200030">
        <core_list id="1" level="10" stat="HEAL_BOOST" value="10"/>
        <core_list id="2" level="20" stat="HEAL_BOOST" value="14"/>
        <core_list id="3" level="30" stat="HEAL_BOOST" value="21"/>
        <core_list id="4" level="40" stat="HEAL_BOOST" value="29"/>
        <core_list id="5" level="50" stat="HEAL_BOOST" value="40"/>
    </cubics_template>
    <cubics_template id="9" name="Bronze Cubelet of Trico Blessing" quality="BRONZE" maxRank="5" category="102" itemId="188200031">
        <core_list id="1" level="20" stat="HEAL_BOOST" value="8"/>
        <core_list id="2" level="40" stat="HEAL_BOOST" value="12"/>
        <core_list id="3" level="60" stat="HEAL_BOOST" value="16"/>
        <core_list id="4" level="80" stat="HEAL_BOOST" value="24"/>
        <core_list id="5" level="100" stat="HEAL_BOOST" value="34"/>
    </cubics_template>
    <cubics_template id="10" name="Gold Cubelet of Worg Madness" quality="GOLD" maxRank="5" category="103" itemId="188200032">
        <core_list id="1" level="5" stat="PHYSICAL_ATTACK" value="33"/>
        <core_list id="2" level="10" stat="PHYSICAL_ATTACK" value="47"/>
        <core_list id="3" level="15" stat="PHYSICAL_ATTACK" value="67"/>
        <core_list id="4" level="20" stat="PHYSICAL_ATTACK" value="101"/>
        <core_list id="5" level="25" stat="PHYSICAL_ATTACK" value="144"/>
    </cubics_template>
    <cubics_template id="11" name="Silver Cubelet of Worg Madness" quality="SILVER" maxRank="5" category="103" itemId="188200033">
        <core_list id="1" level="10" stat="PHYSICAL_ATTACK" value="32"/>
        <core_list id="2" level="20" stat="PHYSICAL_ATTACK" value="46"/>
        <core_list id="3" level="30" stat="PHYSICAL_ATTACK" value="65"/>
        <core_list id="4" level="40" stat="PHYSICAL_ATTACK" value="93"/>
        <core_list id="5" level="50" stat="PHYSICAL_ATTACK" value="125"/>
    </cubics_template>
    <cubics_template id="12" name="Bronze Cubelet of Worg Madness" quality="BRONZE" maxRank="5" category="103" itemId="188200034">
        <core_list id="1" level="20" stat="PHYSICAL_ATTACK" value="26"/>
        <core_list id="2" level="40" stat="PHYSICAL_ATTACK" value="36"/>
        <core_list id="3" level="60" stat="PHYSICAL_ATTACK" value="52"/>
        <core_list id="4" level="80" stat="PHYSICAL_ATTACK" value="74"/>
        <core_list id="5" level="100" stat="PHYSICAL_ATTACK" value="106"/>
    </cubics_template>
    <cubics_template id="13" name="Gold Cubelet of Griffon Wisdom" quality="GOLD" maxRank="5" category="104" itemId="188200035">
        <core_list id="1" level="5" stat="MAGICAL_ATTACK" value="33"/>
        <core_list id="2" level="10" stat="MAGICAL_ATTACK" value="47"/>
        <core_list id="3" level="15" stat="MAGICAL_ATTACK" value="67"/>
        <core_list id="4" level="20" stat="MAGICAL_ATTACK" value="101"/>
        <core_list id="5" level="25" stat="MAGICAL_ATTACK" value="144"/>
    </cubics_template>
    <cubics_template id="14" name="Silver Cubelet of Griffon Wisdom" quality="SILVER" maxRank="5" category="104" itemId="188200036">
        <core_list id="1" level="10" stat="MAGICAL_ATTACK" value="32"/>
        <core_list id="2" level="20" stat="MAGICAL_ATTACK" value="46"/>
        <core_list id="3" level="30" stat="MAGICAL_ATTACK" value="65"/>
        <core_list id="4" level="40" stat="MAGICAL_ATTACK" value="93"/>
        <core_list id="5" level="50" stat="MAGICAL_ATTACK" value="125"/>
    </cubics_template>
    <cubics_template id="15" name="Bronze Cubelet of Griffon Wisdom" quality="BRONZE" maxRank="5" category="104" itemId="188200037">
        <core_list id="1" level="20" stat="MAGICAL_ATTACK" value="26"/>
        <core_list id="2" level="40" stat="MAGICAL_ATTACK" value="36"/>
        <core_list id="3" level="60" stat="MAGICAL_ATTACK" value="52"/>
        <core_list id="4" level="80" stat="MAGICAL_ATTACK" value="74"/>
        <core_list id="5" level="100" stat="MAGICAL_ATTACK" value="106"/>
    </cubics_template>
    <cubics_template id="16" name="Gold Cubelet of Starturtle's Protection" quality="GOLD" maxRank="5" category="105" itemId="188200038">
        <core_list id="1" level="5" stat="PHYSICAL_DEFENSE" value="33"/>
        <core_list id="2" level="10" stat="PHYSICAL_DEFENSE" value="47"/>
        <core_list id="3" level="15" stat="PHYSICAL_DEFENSE" value="67"/>
        <core_list id="4" level="20" stat="PHYSICAL_DEFENSE" value="101"/>
        <core_list id="5" level="25" stat="PHYSICAL_DEFENSE" value="144"/>
    </cubics_template>
    <cubics_template id="17" name="Silver Cubelet of Starturtle's Protection" quality="SILVER" maxRank="5" category="105" itemId="188200039">
        <core_list id="1" level="10" stat="PHYSICAL_DEFENSE" value="32"/>
        <core_list id="2" level="20" stat="PHYSICAL_DEFENSE" value="46"/>
        <core_list id="3" level="30" stat="PHYSICAL_DEFENSE" value="65"/>
        <core_list id="4" level="40" stat="PHYSICAL_DEFENSE" value="93"/>
        <core_list id="5" level="50" stat="PHYSICAL_DEFENSE" value="125"/>
    </cubics_template>
    <cubics_template id="18" name="Bronze Cubelet of Starturtle's Protection" quality="BRONZE" maxRank="5" category="105" itemId="188200040">
        <core_list id="1" level="20" stat="PHYSICAL_DEFENSE" value="26"/>
        <core_list id="2" level="40" stat="PHYSICAL_DEFENSE" value="36"/>
        <core_list id="3" level="60" stat="PHYSICAL_DEFENSE" value="52"/>
        <core_list id="4" level="80" stat="PHYSICAL_DEFENSE" value="74"/>
        <core_list id="5" level="100" stat="PHYSICAL_DEFENSE" value="106"/>
    </cubics_template>
    <cubics_template id="19" name="Gold Cubelet of Scolopen Defence" quality="GOLD" maxRank="5" category="106" itemId="188200041">
        <core_list id="1" level="5" stat="MAGICAL_RESIST" value="33"/>
        <core_list id="2" level="10" stat="MAGICAL_RESIST" value="47"/>
        <core_list id="3" level="15" stat="MAGICAL_RESIST" value="67"/>
        <core_list id="4" level="20" stat="MAGICAL_RESIST" value="101"/>
        <core_list id="5" level="25" stat="MAGICAL_RESIST" value="144"/>
    </cubics_template>
