=== AionGermany/aion-germany/AL-Game-5.8/data/static_data/flypath_template.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="flypath_template">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="flypath_location" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence/>
                        <xs:attribute name="id" type="xs:short" use="required"/>
                        <xs:attribute name="sx" type="xs:float" use="required"/>
                        <xs:attribute name="sy" type="xs:float" use="required"/>
                        <xs:attribute name="sz" type="xs:float" use="required"/>
                        <xs:attribute name="sworld" type="xs:int" use="required"/>
                        <xs:attribute name="ex" type="xs:float" use="required"/>
                        <xs:attribute name="ey" type="xs:float" use="required"/>
                        <xs:attribute name="ez" type="xs:float" use="required"/>
                        <xs:attribute name="eworld" type="xs:int" use="required"/>
                        <xs:attribute name="time" type="xs:float" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== AionGermany/aion-germany/AL-Game-5.8/data/static_data/flypath_template.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- parsed by phpTools from Aion Germany Group (Mariella) at 2018-02-07 19:50 -->
<flypath_template xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="flypath_template.xsd">
    <flypath_location id="1" sx="85.15" sy="189.13" sz="231.34" sworld="310020000" ex="218.85" ey="250.49" ez="206.72" eworld="310020000" time="45"/>
    <flypath_location id="2" sx="85.15" sy="189.13" sz="231.34" sworld="310010000" ex="218.85" ey="250.49" ez="206.72" eworld="310010000" time="45"/>
    <flypath_location id="3" sx="434.19" sy="401.97" sz="233.16" sworld="320020000" ex="308.21" ey="275.45" ez="206.27" eworld="320020000" time="45"/>
    <flypath_location id="4" sx="434.19" sy="401.97" sz="233.16" sworld="320010000" ex="308.21" ey="275.45" ez="206.27" eworld="320010000" time="45"/>
    <flypath_location id="5" sx="806.63" sy="1242.11" sz="119" sworld="210010000" ex="426.17" ey="1742.29" ez="119.85" eworld="210010000" time="38"/>
    <flypath_location id="6" sx="427" sy="1741.83" sz="119.82" sworld="210010000" ex="806.78" ey="1242.13" ez="118.69" eworld="210010000" time="38"/>
    <flypath_location id="7" sx="1642.54" sy="1500.1" sz="119.96" sworld="210030000" ex="2063" ey="2412.5" ez="275" eworld="210030000" time="52"/>
    <flypath_location id="8" sx="2063" sy="2412.5" sz="275" sworld="210030000" ex="1642.68" ey="1500.16" ez="119.92" eworld="210030000" time="51"/>
    <flypath_location id="9" sx="1641.01" sy="1499.98" sz="120.17" sworld="210030000" ex="2382.88" ey="790.39" ez="103.2" eworld="210030000" time="52"/>
    <flypath_location id="10" sx="2382.59" sy="790.31" sz="102.83" sworld="210030000" ex="1641.01" ey="1499.98" ez="119.48" eworld="210030000" time="42.5"/>
    <flypath_location id="11" sx="570.12" sy="2463.74" sz="280.97" sworld="220010000" ex="940.93" ey="1707.49" ez="259.7" eworld="220010000" time="42"/>
    <flypath_location id="12" sx="940.8" sy="1707.1" sz="260.8" sworld="220010000" ex="570.16" ey="2463.66" ez="281.1" eworld="220010000" time="35"/>
    <flypath_location id="13" sx="1752.66" sy="1806.09" sz="254.75" sworld="220030000" ex="2681.8" ey="1025.44" ez="311.94" eworld="220030000" time="49.5"/>
    <flypath_location id="14" sx="2681.53" sy="1027.25" sz="311.44" sworld="220030000" ex="1749.71" ey="1803.79" ez="254.85" eworld="220030000" time="44.5"/>
    <flypath_location id="15" sx="1752.46" sy="1806.71" sz="254.44" sworld="220030000" ex="1903.3" ey="696.8" ez="260.7" eworld="220030000" time="41"/>
    <flypath_location id="16" sx="1903.3" sy="696.8" sz="260.7" sworld="220030000" ex="1752.41" ey="1806.6" ez="254.76" eworld="220030000" time="41"/>
    <flypath_location id="17" sx="2415.73" sy="2728.43" sz="361.75" sworld="210020000" ex="2415.15" ey="2727.66" ez="361.65" eworld="210020000" time="40"/>
    <flypath_location id="18" sx="345" sy="2723" sz="264" sworld="210020000" ex="687" ey="432" ez="332" eworld="210020000" time="55"/>
    <flypath_location id="19" sx="687" sy="432" sz="332" sworld="210020000" ex="345" ey="2723" ez="264" eworld="210020000" time="51"/>
    <flypath_location id="20" sx="345" sy="2723" sz="264" sworld="210020000" ex="1922.3" ey="2043.6" ez="363" eworld="210020000" time="46"/>
    <flypath_location id="21" sx="1922.3" sy="2043.6" sz="363" sworld="210020000" ex="345" ey="2723" ez="264" eworld="210020000" time="48"/>
    <flypath_location id="22" sx="687" sy="432" sz="332" sworld="210020000" ex="1922.3" ey="2043.6" ez="363" eworld="210020000" time="53"/>
    <flypath_location id="23" sx="1922.3" sy="2043.6" sz="363" sworld="210020000" ex="687" ey="432" ez="332" eworld="210020000" time="53"/>
    <flypath_location id="24" sx="310" sy="2271" sz="450" sworld="220020000" ex="634" ey="900" ez="361" eworld="220020000" time="46"/>
    <flypath_location id="25" sx="310" sy="2271" sz="450" sworld="220020000" ex="2387.8" ey="1742" ez="103" eworld="220020000" time="75"/>
    <flypath_location id="26" sx="634" sy="900" sz="361" sworld="220020000" ex="310" ey="2271" ez="450" eworld="220020000" time="56"/>
    <flypath_location id="27" sx="634" sy="900" sz="361" sworld="220020000" ex="2387.8" ey="1742" ez="103" eworld="220020000" time="55"/>
    <flypath_location id="28" sx="2387.8" sy="1742" sz="103" sworld="220020000" ex="310" ey="2271" ez="450" eworld="220020000" time="90"/>
    <flypath_location id="29" sx="2387.8" sy="1742" sz="103" sworld="220020000" ex="634" ey="900" ez="361" eworld="220020000" time="61"/>
    <flypath_location id="30" sx="2788.62" sy="487.7" sz="267.89" sworld="220020000" ex="2015" ey="714" ez="263" eworld="220020000" time="45"/>
    <flypath_location id="31" sx="339.82" sy="104.53" sz="1189.98" sworld="310070000" ex="202.82" ey="274.66" ez="1375.89" eworld="310070000" time="46"/>
    <flypath_location id="32" sx="1392.23" sy="195.34" sz="1567.15" sworld="400010000" ex="1345.59" ey="261.74" ez="2843.34" eworld="400010000" time="26.5"/>
    <flypath_location id="33" sx="1346.62" sy="262.4" sz="2843.26" sworld="400010000" ex="1392.22" ey="195.3" ez="1567.15" eworld="400010000" time="29.6"/>
    <flypath_location id="34" sx="1349.11" sy="2709.56" sz="1667.15" sworld="400010000" ex="1302.14" ey="2777.02" ez="2943.26" eworld="400010000" time="26.5"/>
    <flypath_location id="35" sx="1297.01" sy="2777.69" sz="2943.43" sworld="400010000" ex="1347.76" ey="2707.15" ez="1667.14" eworld="400010000" time="29.6"/>
    <flypath_location id="36" sx="1391.79" sy="351.1" sz="1569.05" sworld="400010000" ex="1430.47" ey="253.86" ez="2843.63" eworld="400010000" time="26.5"/>
    <flypath_location id="37" sx="1426.75" sy="255.2" sz="2843.55" sworld="400010000" ex="1389.75" ey="352.1" ez="1569" eworld="400010000" time="29.5"/>
    <flypath_location id="38" sx="1346.41" sy="2867.06" sz="1669.05" sworld="400010000" ex="1385.92" ey="2769.64" ez="2943.52" eworld="400010000" time="26.5"/>
    <flypath_location id="39" sx="1385.36" sy="2769.61" sz="2943.5" sworld="400010000" ex="1348.51" ey="2867.73" ez="1668.96" eworld="400010000" time="29.5"/>
    <flypath_location id="40" sx="2542.3" sy="339.3" sz="412" sworld="210040000" ex="1423.8" ey="1334.4" ez="175" eworld="210040000" time="49"/>
    <flypath_location id="41" sx="1423.8" sy="1334.4" sz="175" sworld="210040000" ex="2542.3" ey="339.3" ez="412" eworld="210040000" time="39"/>
    <flypath_location id="42" sx="2542.3" sy="339.3" sz="412" sworld="210040000" ex="171" ey="1663" ez="121" eworld="210040000" time="73"/>
    <flypath_location id="43" sx="171" sy="1663" sz="121" sworld="210040000" ex="2542.3" ey="339.3" ez="412" eworld="210040000" time="69"/>
    <flypath_location id="44" sx="2542.3" sy="339.3" sz="412" sworld="210040000" ex="1635.1" ey="2693.4" ez="116" eworld="210040000" time="66"/>
    <flypath_location id="45" sx="1635.1" sy="2693.4" sz="116" sworld="210040000" ex="2542.3" ey="339.3" ez="412" eworld="210040000" time="69"/>
    <flypath_location id="46" sx="171" sy="1663" sz="121" sworld="210040000" ex="1635.1" ey="2693.4" ez="116" eworld="210040000" time="51"/>
    <flypath_location id="47" sx="1635.1" sy="2693.4" sz="116" sworld="210040000" ex="171" ey="1663" ez="121" eworld="210040000" time="50"/>
    <flypath_location id="48" sx="398.3" sy="400.8" sz="223" sworld="220040000" ex="533.7" ey="1866.9" ez="262" eworld="220040000" time="51"/>
    <flypath_location id="49" sx="533.7" sy="1866.9" sz="262" sworld="220040000" ex="398.3" ey="400.8" ez="223" eworld="220040000" time="51"/>
    <flypath_location id="50" sx="398.3" sy="400.8" sz="223" sworld="220040000" ex="2359" ey="1241" ez="470" eworld="220040000" time="53"/>
    <flypath_location id="51" sx="2359" sy="1241" sz="470" sworld="220040000" ex="398.3" ey="400.8" ez="223" eworld="220040000" time="61"/>
    <flypath_location id="52" sx="533.7" sy="1866.9" sz="262" sworld="220040000" ex="2359" ey="1241" ez="470" eworld="220040000" time="58"/>
    <flypath_location id="53" sx="2359" sy="1241" sz="470" sworld="220040000" ex="533.7" ey="1866.9" ez="262" eworld="220040000" time="56"/>
    <flypath_location id="54" sx="2032" sy="1401" sz="118" sworld="210040000" ex="2878" ey="2180" ez="153" eworld="210040000" time="51"/>
    <flypath_location id="55" sx="138.62" sy="791.5" sz="2836.51" sworld="400010000" ex="2785.53" ey="2077.4" ez="2766.73" eworld="400010000" time="32.4"/>
    <flypath_location id="56" sx="2784.93" sy="2078.32" sz="2767" sworld="400010000" ex="137.15" ey="790.86" ez="2836.53" eworld="400010000" time="32.4"/>
    <flypath_location id="57" sx="138.62" sy="791.5" sz="2836.51" sworld="400010000" ex="2785.53" ey="2077.4" ez="2766.73" eworld="400010000" time="32.4"/>
    <flypath_location id="58" sx="2784.93" sy="2078.32" sz="2767" sworld="400010000" ex="137.15" ey="790.86" ez="2836.53" eworld="400010000" time="32.4"/>
    <flypath_location id="59" sx="1396.2" sy="1560" sz="32" sworld="210060000" ex="2234.9" ey="2284.5" ez="51" eworld="210060000" time="42"/>
    <flypath_location id="60" sx="2234.9" sy="2284.5" sz="51" sworld="210060000" ex="1396.2" ey="1560" ez="32" eworld="210060000" time="37.4"/>
    <flypath_location id="61" sx="2234.9" sy="2284.5" sz="51" sworld="210060000" ex="458.5" ey="1257.7" ez="128" eworld="210060000" time="47.6"/>
    <flypath_location id="62" sx="458.5" sy="1257.7" sz="128" sworld="210060000" ex="2234.9" ey="2284.5" ez="51" eworld="210060000" time="60.4"/>
    <flypath_location id="63" sx="458.5" sy="1257.7" sz="128" sworld="210060000" ex="1396.2" ey="1560" ez="32" eworld="210060000" time="29.8"/>
    <flypath_location id="64" sx="1396.2" sy="1560" sz="32" sworld="210060000" ex="458.5" ey="1257.7" ez="128" eworld="210060000" time="35"/>
    <flypath_location id="65" sx="2917.3" sy="2417.5" sz="16" sworld="220050000" ex="1413.2" ey="2013" ez="52.5" eworld="220050000" time="53"/>
