=== AionGermany/aion-germany/AL-Game-5.8/data/static_data/teleport_location.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="teleport_location">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="teleloc_template" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence/>
                        <xs:attribute name="loc_id" type="xs:int" use="required"/>
                        <xs:attribute name="mapid" type="xs:int" use="required"/>
                        <xs:attribute name="name" type="xs:string" use="required"/>
                        <xs:attribute name="name_id" type="xs:int" use="required"/>
                        <xs:attribute name="teleportid" type="xs:int"/>
                        <xs:attribute name="posX" type="xs:float"/>
                        <xs:attribute name="posY" type="xs:float"/>
                        <xs:attribute name="posZ" type="xs:float"/>
                        <xs:attribute name="heading" type="xs:int"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== AionGermany/aion-germany/AL-Game-5.8/data/static_data/teleport_location.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- parsed by phpTools from Aion Germany Group (Mariella) at 2018-02-07 20:24 -->
<teleport_location xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="teleport_location.xsd">
    <!-- teleport -->
    <teleloc_template loc_id="2" mapid="110010000" name="Sanctum" name_id="400489" posX="1313.25" posY="1512.011" posZ="568.107" heading="0"/>
    <teleloc_template loc_id="3" mapid="210010000" name="Poeta" name_id="400490" posX="805.9061" posY="1242.6946" posZ="118.75" heading="100"/>
    <teleloc_template loc_id="4" mapid="210030000" name="Verteron" name_id="400491" posX="1640.76" posY="1500.32" posZ="119.70999" heading="0"/>
    <teleloc_template loc_id="5" mapid="210020000" name="Eltnen" name_id="400492" posX="344.48312" posY="2723.4956" posZ="263.88733" heading="45"/>
    <teleloc_template loc_id="6" mapid="210040000" name="Heiron" name_id="400493" posX="2542.2327" posY="339.2828" posZ="411.66394" heading="36"/>
    <teleloc_template loc_id="7" mapid="120010000" name="Pandaemonium" name_id="400494" posX="1685.7" posY="1400.5" posZ="195.48618" heading="60"/>
    <teleloc_template loc_id="8" mapid="220010000" name="Ishalgen" name_id="400495" posX="570.40451" posY="2462.6885" posZ="280.94876" heading="106"/>
    <teleloc_template loc_id="9" mapid="220030000" name="Altgard" name_id="400496" posX="1752.5322" posY="1806.6096" posZ="254.66133" heading="60"/>
    <teleloc_template loc_id="10" mapid="220020000" name="Morheim" name_id="400497" posX="309.53" posY="2271.51" posZ="449.41266" heading="0"/>
    <teleloc_template loc_id="11" mapid="220040000" name="Beluslan" name_id="400498" posX="398.3" posY="400.8" posZ="222.79721" heading="23"/>
    <!-- flying -->
    <teleloc_template loc_id="12" mapid="210010000" name="Akarios Village" name_id="400499"/>
    <teleloc_template loc_id="13" mapid="210010000" name="Melponeh's Campsite" name_id="400500"/>
    <teleloc_template loc_id="14" mapid="210030000" name="Verteron Citadel" name_id="400501"/>
    <teleloc_template loc_id="15" mapid="210030000" name="Pilgrims Respite" name_id="400502"/>
    <teleloc_template loc_id="16" mapid="210030000" name="Verteron Observatory" name_id="400503"/>
    <teleloc_template loc_id="17" mapid="220010000" name="Aldelle Village" name_id="400504"/>
    <teleloc_template loc_id="18" mapid="220010000" name="Anturoon Crossing" name_id="400505"/>
    <teleloc_template loc_id="19" mapid="220030000" name="Altgard Fortress" name_id="400506"/>
    <teleloc_template loc_id="20" mapid="220030000" name="Trader's Berth" name_id="400507"/>
    <teleloc_template loc_id="21" mapid="210020000" name="Eltnen Fortress" name_id="400593"/>
    <teleloc_template loc_id="22" mapid="210020000" name="Golden Bough Garrison" name_id="400594"/>
    <teleloc_template loc_id="23" mapid="210020000" name="Agairon Village" name_id="400595"/>
    <!-- teleport -->
    <teleloc_template loc_id="24" mapid="110010000" name="Elyos Square" name_id="400508" posX="1458.6332" posY="1450.5676" posZ="572.87573" heading="15"/>
    <teleloc_template loc_id="25" mapid="110010000" name="Divine Road" name_id="400509" posX="1930.9808" posY="1514.3209" posZ="590.01074" heading="60"/>
    <!-- flying -->
    <teleloc_template loc_id="28" mapid="210040000" name="New Heiron Gate" name_id="400596"/>
    <teleloc_template loc_id="29" mapid="210040000" name="Heiron Observatory" name_id="400597"/>
    <teleloc_template loc_id="30" mapid="210040000" name="Arbolu's Haven" name_id="400598"/>
    <teleloc_template loc_id="31" mapid="210040000" name="Jeiaparan Village" name_id="400599"/>
    <teleloc_template loc_id="32" mapid="220030000" name="Basfelt Village" name_id="400600"/>
    <!-- teleport -->
    <teleloc_template loc_id="33" mapid="120010000" name="Vifrost Bridge" name_id="400606" posX="1601.8434" posY="1412.9706" posZ="193.1286" heading="0"/>
    <teleloc_template loc_id="34" mapid="120010000" name="Prosperity Road" name_id="400607" posX="1034.8004" posY="1473.1919" posZ="213.4775" heading="105"/>
    <teleloc_template loc_id="35" mapid="400010000" name="Teminon Landing" name_id="400658" posX="2865.86" posY="1036.57" posZ="1528.12" heading="44"/>
    <teleloc_template loc_id="36" mapid="400010000" name="Siel's Western Fortress" name_id="400659" posX="2985.3564" posY="2595.3398" posZ="1489.0905" heading="33"/>
    <teleloc_template loc_id="37" mapid="400010000" name="Siel's Eastern Fortress" name_id="400660" posX="2656.2722" posY="3063.4211" posZ="1483.1167" heading="33"/>
    <teleloc_template loc_id="38" mapid="400010000" name="Primum Landing" name_id="400661" posX="1078.71" posY="2838.54" posZ="1636.58" heading="0"/>
    <teleloc_template loc_id="39" mapid="400010000" name="Sulphur Fortress" name_id="400662" posX="1345.1719" posY="1190.9126" posZ="1514.6681" heading="41"/>
    <teleloc_template loc_id="40" mapid="400010000" name="Eastern Shard of Latesran" name_id="400666" posX="1346" posY="2866" posZ="1668" heading="90"/>
    <!-- flying -->
    <teleloc_template loc_id="41" mapid="400010000" name="Eastern Shard of Latesran" name_id="400667"/>
    <!-- teleport -->
    <teleloc_template loc_id="42" mapid="400010000" name="Western Shard of Latesran" name_id="400668" posX="1390" posY="352" posZ="1568" heading="30"/>
    <!-- flying -->
    <teleloc_template loc_id="43" mapid="400010000" name="Western Shard of Latesran" name_id="400669"/>
    <!-- teleport -->
    <teleloc_template loc_id="44" mapid="400010000" name="Roah Fortress" name_id="400685" posX="2711.9102" posY="774.9118" posZ="2872.3818" heading="93"/>
    <teleloc_template loc_id="45" mapid="400010000" name="Krotan Refuge" name_id="400686" posX="1429.6635" posY="930.90173" posZ="2963.221" heading="60"/>
    <teleloc_template loc_id="46" mapid="400010000" name="Kysis Fortress" name_id="400687" posX="1919.2158" posY="1726.3091" posZ="3015.5928" heading="93"/> <!--updated -->
    <teleloc_template loc_id="47" mapid="400010000" name="Miren Fortress" name_id="400688" posX="1175.4662" posY="1939.7646" posZ="2949.5" heading="8"/> <!--updated -->
    <teleloc_template loc_id="48" mapid="400010000" name="Asteria Fortress" name_id="400689" posX="717.2298" posY="3002.2446" posZ="2893.0178" heading="16"/>
    <teleloc_template loc_id="49" mapid="400010000" name="Divine Fortress" name_id="400690" posX="2125.776" posY="1913.0077" posZ="2322.0728" heading="72"/>
    <teleloc_template loc_id="50" mapid="400010000" name="Eastern Shard of Latesran" name_id="400721" posX="1348" posY="2710" posZ="1667" heading="90"/>
    <!-- flying -->
    <teleloc_template loc_id="51" mapid="400010000" name="Eastern Shard of Latesran" name_id="400722"/>
    <!-- teleport -->
    <teleloc_template loc_id="52" mapid="400010000" name="Western Shard of Latesran" name_id="400723" posX="1392" posY="195" posZ="1567" heading="90"/>
    <!-- flying -->
    <teleloc_template loc_id="53" mapid="400010000" name="Western Shard of Latesran" name_id="400724"/>
    <!-- teleport -->
    <teleloc_template loc_id="54" mapid="400010000" name="Siel's Western Fortress" name_id="400725" posX="2985.3564" posY="2595.3398" posZ="1489.0905" heading="33"/>
    <teleloc_template loc_id="55" mapid="400010000" name="Siel's Eastern Fortress" name_id="400726" posX="2656.2722" posY="3063.4211" posZ="1483.1167" heading="33"/>
    <teleloc_template loc_id="56" mapid="400010000" name="Sulphur Fortress" name_id="400727" posX="1345.1719" posY="1190.9126" posZ="1514.6681" heading="41"/>
    <teleloc_template loc_id="57" mapid="400010000" name="Krotan Refuge" name_id="400729" posX="2033.38" posY="1294.35" posZ="2963.57" heading="60"/>
    <teleloc_template loc_id="58" mapid="400010000" name="Kysis Fortress" name_id="400730" posX="1919.1362" posY="1726.4082" posZ="3015.5928" heading="93"/>
    <teleloc_template loc_id="59" mapid="400010000" name="Miren Fortress" name_id="400731" posX="1175.0942" posY="1945.7646" posZ="2949.6787" heading="8"/>
    <teleloc_template loc_id="60" mapid="400010000" name="Asteria Fortress" name_id="400732" posX="715.97736" posY="2999.419" posZ="2893.0176" heading="15"/>
    <teleloc_template loc_id="61" mapid="400010000" name="Divine Fortress" name_id="400733" posX="2125.776" posY="1913.0077" posZ="2322.0728" heading="72"/>
    <teleloc_template loc_id="62" mapid="400010000" name="Roah Fortress" name_id="400728" posX="2711.9102" posY="774.9118" posZ="2872.3818" heading="93"/>
    <!-- flying -->
    <teleloc_template loc_id="63" mapid="220020000" name="Morheim Ice Fortress" name_id="400740"/>
    <teleloc_template loc_id="64" mapid="220020000" name="Desert Garrison" name_id="400741"/>
    <teleloc_template loc_id="65" mapid="220020000" name="Alsig Village" name_id="400742"/>
    <!-- teleport -->
    <teleloc_template loc_id="72" mapid="400010000" name="Krotan Refuge Area" name_id="400882" posX="2033.3788" posY="1294.3495" posZ="2963.5703" heading="60"/>
    <teleloc_template loc_id="73" mapid="400010000" name="Kysis Fortress Area" name_id="400883" posX="2533.71" posY="2090.47" posZ="3049.97" heading="91"/>
    <teleloc_template loc_id="74" mapid="400010000" name="Miren Fortress Area" name_id="400884" posX="1789.7555" posY="2314.2678" posZ="2949.6802" heading="7"/>
    <teleloc_template loc_id="75" mapid="400010000" name="Krotan Refuge Area" name_id="400885" posX="2033.3788" posY="1294.3495" posZ="2963.5703" heading="60"/>
    <teleloc_template loc_id="76" mapid="400010000" name="Kysis Fortress Area" name_id="400886" posX="2533.71" posY="2090.47" posZ="3049.97" heading="91"/>
    <teleloc_template loc_id="77" mapid="400010000" name="Miren Fortress Area" name_id="400887" posX="1789.7555" posY="2314.2678" posZ="2949.6802" heading="7"/>
    <!-- flying -->
    <teleloc_template loc_id="78" mapid="220040000" name="Beluslan Fortress" name_id="400929"/>
