=== AionGermany/aion-germany/AL-Game-5.8/data/static_data/world_maps.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="world_maps">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" name="map">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element minOccurs="0" maxOccurs="1" name="ai_info" type="AiInfo"/>
                        </xs:sequence>
                        <xs:attribute name="name" type="xs:string"/>
                        <xs:attribute name="id" type="xs:int" use="required"/>
                        <xs:attribute name="twin_count" type="xs:int"/>
                        <xs:attribute name="beginner_twin_count" type="xs:int"/>
                        <xs:attribute name="max_user" type="xs:int"/>
                        <xs:attribute name="prison" type="xs:boolean"/>
                        <xs:attribute name="instance" type="xs:boolean"/>
                        <xs:attribute name="looting_level" type="xs:int" use="optional"/>
                        <xs:attribute name="looting_auth" type="xs:string" use="optional"/>
                        <xs:attribute name="water_level" type="xs:int" use="required"/>
                        <xs:attribute name="death_level" type="xs:int" use="required"/>
                        <xs:attribute name="world_type" type="worldType"/>
                        <xs:attribute name="world_size" type="xs:int" use="required"/>
                        <xs:attribute name="except_buff" type="xs:boolean"/>
                        <xs:attribute name="flags" type="AttributeList" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="AiInfo">
        <xs:attribute default="50" name="chase_target" type="xs:int"/>
        <xs:attribute default="200" name="chase_home" type="xs:int"/>
    </xs:complexType>
    <xs:simpleType name="worldType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="ASMODAE"/>
            <xs:enumeration value="ELYSEA"/>
            <xs:enumeration value="BALAUREA"/>
            <xs:enumeration value="ABYSS"/>
            <xs:enumeration value="NONE"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="ZoneAttributes">
        <xs:restriction base="xs:string">
            <xs:enumeration value="BIND"/>
            <xs:enumeration value="RECALL"/>
            <xs:enumeration value="GLIDE"/>
            <xs:enumeration value="FLY"/>
            <xs:enumeration value="RIDE"/>
            <xs:enumeration value="FLY_RIDE"/>
            <xs:enumeration value="PVP"/>
            <xs:enumeration value="DUEL_SAME_RACE"/>
            <xs:enumeration value="DUEL_OTHER_RACE"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="AttributeList">
        <xs:list itemType="ZoneAttributes"/>
    </xs:simpleType>
</xs:schema>

=== AionGermany/aion-germany/AL-Game-5.8/data/static_data/world_maps.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- parsed by phpTools from Aion Germany Group (Mariella) at 2018-03-12 14:13 -->
<world_maps xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="world_maps.xsd">
    <map id="110010000" name="Sanctum" death_level="400" water_level="16" world_type="ELYSEA" world_size="3072" flags="RECALL GLIDE RIDE FLY_RIDE PVP DUEL_SAME_RACE"/>
    <map id="110020000" name="Cloister of Kaisinel" death_level="0" water_level="16" world_type="ELYSEA" world_size="3072" flags="RECALL GLIDE RIDE FLY_RIDE PVP DUEL_SAME_RACE"/>
    <map id="120010000" name="Pandaemonium" death_level="150" water_level="16" world_type="ASMODAE" world_size="3072" flags="RECALL GLIDE RIDE FLY_RIDE PVP DUEL_SAME_RACE"/>
    <map id="120020000" name="Convent of Marchutan" death_level="0" water_level="16" world_type="ASMODAE" world_size="3072" flags="RECALL RIDE FLY_RIDE PVP DUEL_SAME_RACE"/>
    <map id="110070000" name="Kaisinel Academy" death_level="0" water_level="16" world_type="ELYSEA" world_size="1024" flags="RECALL GLIDE RIDE FLY_RIDE PVP DUEL_SAME_RACE"/>
    <map id="120080000" name="Marchutan Priory" death_level="0" water_level="3" world_type="ASMODAE" world_size="1024" flags="RECALL RIDE FLY_RIDE PVP DUEL_SAME_RACE"/>
    <map id="130090000" name="Refuge of Returnees" death_level="0" water_level="3" world_type="ELYSEA" world_size="1024" flags="RECALL RIDE FLY_RIDE PVP DUEL_SAME_RACE"/>
    <map id="140010000" name="Refuge of Returnees" death_level="0" water_level="3" world_type="ASMODAE" world_size="1024" flags="RECALL RIDE FLY_RIDE PVP DUEL_SAME_RACE"/>
    <map id="210010000" name="Poeta" twin_count="2" beginner_twin_count="6" max_user="200" death_level="0" water_level="100" world_type="ELYSEA" world_size="3072" flags="BIND RECALL GLIDE PVP DUEL_SAME_RACE"/>
    <map id="210020000" name="Eltnen" beginner_twin_count="5" death_level="0" water_level="6" world_type="ELYSEA" world_size="3072" flags="BIND RECALL GLIDE RIDE FLY_RIDE PVP DUEL_SAME_RACE"/>
    <map id="210030000" name="Verteron" twin_count="3" beginner_twin_count="4" max_user="200" death_level="0" water_level="100" world_type="ELYSEA" world_size="3072" flags="BIND RECALL GLIDE RIDE FLY_RIDE PVP DUEL_SAME_RACE"/>
    <map id="210040000" name="Heiron" beginner_twin_count="3" death_level="0" water_level="100" world_type="ELYSEA" world_size="3072" flags="BIND RECALL GLIDE RIDE FLY_RIDE PVP DUEL_SAME_RACE"/>
    <map id="210050000" name="Inggison" death_level="0" water_level="16" world_type="BALAUREA" world_size="3072" flags="BIND RECALL GLIDE RIDE FLY_RIDE PVP DUEL_SAME_RACE"/>
    <map id="210060000" name="Theobomos" twin_count="1" beginner_twin_count="2" death_level="0" water_level="1" world_type="ELYSEA" world_size="3072" flags="BIND RECALL GLIDE RIDE FLY_RIDE PVP DUEL_SAME_RACE"/>
    <map id="210070000" name="Signia" death_level="0" water_level="16" world_type="BALAUREA" world_size="3072" flags="BIND RECALL GLIDE RIDE FLY_RIDE PVP DUEL_SAME_RACE"/>
    <map id="210080000" name="Griffoen" death_level="0" water_level="16" world_type="BALAUREA" world_size="512" flags="BIND RECALL GLIDE RIDE FLY_RIDE PVP DUEL_SAME_RACE"/>
    <map id="210090000" name="Katalam Underground" death_level="0" water_level="16" world_type="BALAUREA" world_size="1536" flags="BIND RECALL GLIDE RIDE FLY_RIDE PVP DUEL_SAME_RACE"/>
    <map id="210100000" name="Esterra" twin_count="1" death_level="0" water_level="16" world_type="ELYSEA" world_size="3072" flags="BIND RECALL GLIDE RIDE FLY_RIDE PVP DUEL_SAME_RACE"/>
    <map id="210110000" name="Tower of Eternity" death_level="0" water_level="16" world_type="ELYSEA" world_size="1024" flags="BIND RECALL GLIDE RIDE FLY_RIDE PVP DUEL_SAME_RACE"/>
    <map id="210120000" name="Arena_event_L" instance="true" death_level="0" water_level="16" world_type="ELYSEA" world_size="1024" flags="BIND RECALL GLIDE RIDE FLY_RIDE PVP DUEL_SAME_RACE"/>
    <map id="210130000" name="Inggison" death_level="0" water_level="16" world_type="BALAUREA" world_size="3072" flags="BIND RECALL GLIDE RIDE FLY_RIDE PVP DUEL_SAME_RACE"/>
    <map id="220010000" name="Ishalgen" twin_count="2" beginner_twin_count="6" max_user="200" death_level="0" water_level="248" world_type="ASMODAE" world_size="3072" flags="BIND RECALL PVP DUEL_SAME_RACE"/>
    <map id="220020000" name="Morheim" beginner_twin_count="5" death_level="0" water_level="16" world_type="ASMODAE" world_size="3072" flags="BIND RECALL GLIDE RIDE FLY_RIDE PVP DUEL_SAME_RACE"/>
    <map id="220030000" name="Altgard" twin_count="3" beginner_twin_count="4" max_user="200" death_level="0" water_level="200" world_type="ASMODAE" world_size="3072" flags="BIND RECALL GLIDE RIDE FLY_RIDE PVP DUEL_SAME_RACE"/>
    <map id="220040000" name="Beluslan" beginner_twin_count="3" death_level="0" water_level="16" world_type="ASMODAE" world_size="3072" flags="BIND RECALL GLIDE RIDE FLY_RIDE PVP DUEL_SAME_RACE"/>
    <map id="220050000" name="Brusthonin" twin_count="1" beginner_twin_count="2" death_level="0" water_level="5" world_type="ASMODAE" world_size="3072" flags="BIND RECALL GLIDE RIDE FLY_RIDE PVP DUEL_SAME_RACE"/>
    <map id="220070000" name="Gelkmaros" death_level="0" water_level="16" world_type="BALAUREA" world_size="3072" flags="BIND RECALL GLIDE RIDE FLY_RIDE PVP DUEL_SAME_RACE"/>
    <map id="220080000" name="Vengar" death_level="0" water_level="16" world_type="BALAUREA" world_size="3072" flags="BIND RECALL GLIDE RIDE FLY_RIDE PVP DUEL_SAME_RACE"/>
    <map id="220090000" name="Habrok" death_level="0" water_level="16" world_type="BALAUREA" world_size="512" flags="BIND RECALL GLIDE RIDE FLY_RIDE PVP DUEL_SAME_RACE"/>
    <map id="220100000" name="Katalam Underground" death_level="0" water_level="16" world_type="BALAUREA" world_size="1536" flags="BIND RECALL GLIDE RIDE FLY_RIDE PVP DUEL_SAME_RACE"/>
    <map id="220110000" name="Nosra" twin_count="1" death_level="0" water_level="16" world_type="ASMODAE" world_size="3072" flags="BIND RECALL GLIDE RIDE FLY_RIDE PVP DUEL_SAME_RACE"/>
    <map id="220120000" name="Tower of Eternity" death_level="0" water_level="16" world_type="ASMODAE" world_size="1024" flags="BIND RECALL GLIDE RIDE FLY_RIDE PVP DUEL_SAME_RACE"/>
    <map id="220130000" name="Arena_event_D" instance="true" death_level="0" water_level="16" world_type="ASMODAE" world_size="1024" flags="BIND RECALL GLIDE RIDE FLY_RIDE PVP DUEL_SAME_RACE"/>
    <map id="220140000" name="Gelkmaros" death_level="0" water_level="16" world_type="BALAUREA" world_size="3072" flags="BIND RECALL GLIDE RIDE FLY_RIDE PVP DUEL_SAME_RACE"/>
    <map id="300010000" name="IDAbPro" instance="true" death_level="0" water_level="16" world_size="512" flags="BIND RECALL GLIDE RIDE FLY_RIDE PVP DUEL_SAME_RACE"/>
    <map id="300020000" name="IDTest_Dungeon" death_level="0" water_level="16" world_size="256" flags="BIND RECALL GLIDE FLY RIDE FLY_RIDE PVP DUEL_SAME_RACE DUEL_OTHER_RACE"/>
    <map id="300030000" name="Nochsana Training Camp" instance="true" death_level="0" water_level="16" world_type="ABYSS" world_size="1024" flags="PVP DUEL_SAME_RACE"/>
    <map id="300040000" name="Dark Poeta" instance="true" death_level="0" water_level="16" world_type="ABYSS" world_size="1536" flags="PVP DUEL_SAME_RACE"/>
    <map id="300050000" name="Gale Island Treasure Chamber" instance="true" death_level="0" water_level="16" world_type="ABYSS" world_size="1024" flags="RECALL PVP DUEL_SAME_RACE"/>
    <map id="300060000" name="Sulphur Tree Nest" instance="true" looting_level="18" death_level="0" water_level="16" world_type="ABYSS" world_size="1024" flags="RECALL PVP DUEL_SAME_RACE"/>
    <map id="300070000" name="Zephyr Island Treasure Chamber" instance="true" death_level="0" water_level="16" world_type="ABYSS" world_size="1024" flags="RECALL PVP DUEL_SAME_RACE"/>
    <map id="300080000" name="Left Wing Chamber" instance="true" looting_level="18" death_level="0" water_level="16" world_type="ABYSS" world_size="1024" flags="RECALL PVP DUEL_SAME_RACE"/>
    <map id="300090000" name="Right Wing Chamber" instance="true" looting_level="18" death_level="0" water_level="16" world_type="ABYSS" world_size="512" flags="RECALL PVP DUEL_SAME_RACE"/>
    <map id="300100000" name="Steel Rake" instance="true" death_level="0" water_level="16" world_size="1024" flags="RECALL PVP DUEL_SAME_RACE"/>
    <map id="300110000" name="Baranath Dredgion" instance="true" death_level="0" water_level="16" world_size="1024" except_buff="true" flags="PVP DUEL_SAME_RACE">
        <ai_info chase_target="100" chase_home="1024"/>
    </map>
    <map id="300120000" name="Krakon's Dispute Treasure Chamber" instance="true" death_level="0" water_level="16" world_type="ABYSS" world_size="1024" flags="RECALL PVP DUEL_SAME_RACE"/>
    <map id="300130000" name="Twilight Battlefield Treasure Chamber" instance="true" death_level="0" water_level="16" world_type="ABYSS" world_size="1024" flags="RECALL PVP DUEL_SAME_RACE"/>
    <map id="300140000" name="Isle of Roots Treasure Chamber" instance="true" death_level="0" water_level="16" world_type="ABYSS" world_size="1024" flags="RECALL PVP DUEL_SAME_RACE"/>
    <map id="300150000" name="Udas Temple" instance="true" death_level="0" water_level="16" world_size="1024" flags="PVP DUEL_SAME_RACE"/>
    <map id="300160000" name="Lower Udas Temple" instance="true" death_level="0" water_level="16" world_size="2048" flags="PVP DUEL_SAME_RACE"/>
    <map id="300170000" name="Beshmundir Temple" instance="true" death_level="0" water_level="100" world_type="BALAUREA" world_size="2048" flags="PVP DUEL_SAME_RACE"/>
    <map id="300190000" name="Taloc's Hollow" instance="true" death_level="0" water_level="16" world_size="2048" flags="PVP DUEL_SAME_RACE"/>
    <map id="300200000" name="Haramel" instance="true" death_level="0" water_level="16" world_size="512" flags="GLIDE PVP DUEL_SAME_RACE"/>
